name: Update outages.json

on:
  schedule:
    - cron: '*/15 * * * *'  # Every 15 minutes
  workflow_dispatch:        # Manual run button

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4

      - name: Run scraper
        run: python fetch_nbpower_outages.py

      - name: Commit & Push if changed
        run: |
          git config --global user.email "merrillspencer@live.ca"
          git config --global user.name "Merrill Spencer"
          git add outages.json
          git commit -m "Auto-update outages.json" || echo "No changes to commit"
          git push
