name: Update Outages

on:
  schedule:
    - cron: "*/15 * * * *"  # Every 15 minutes
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Playwright browser
        run: |
          python -m playwright install --with-deps

      - name: Run scraper
        run: |
          python scrape_outages.py
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add outages.json touch.txt
          git commit -m "Update outage data" || echo "No changes to commit"
          git push
